spring:
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: root
    url: jdbc:mysql:///openapi-admin
    #type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: rabbitmq.qfjava.cn
    port: 8800
